Manage communication
green-fox-academy/huli-kalendaryo-android pull request #22
Opened 2018-01-09 13:00 UTC by dzlica

2018-01-09 13:22 UTC, adamgyulavari requested changes

2018-01-09 13:22 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/kalendaryo/LoginActivity.java
> +            apiService.postAuth(clientToken, new KalAuth(account.getServerAuthCode(), userEmail, userName, clientToken)).enqueue(new Callback<KalUser>() {
we dont need the `clientToken` variable

2018-01-09 13:22 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/kalendaryo/LoginActivity.java
> +        kalPref.putSting("clienttoken", clientToken);
lets just rename this to putString :)

2018-01-09 13:22 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/kalendaryo/models/KalPref.java
> +    public void putAuth(String key, KalAuth kalAuth) {
we dont actually need the key, because its inside of `kalAuth`

2018-01-09 13:22 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/kalendaryo/models/KalPref.java
> +        this.putSting(key, value);
use `kalAuth.getEmail()` for the key

2018-01-09 13:22 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/kalendaryo/models/KalPref.java
> +    public void addAccount(String accountname) {
so this should be `private`

2018-01-09 13:22 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/kalendaryo/models/KalPref.java
> +    }
so let's call the store the key method here as well

2018-01-09 13:22 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/kalendaryo/LoginActivity.java
> +            String clientToken = kalPref.getString("clienttoken");
let's refactor this into a `kalPref.clientToken()` and while you're there let's have this `"clienttoken"` string extracted into a constant of `KalPref` class

2018-01-09 13:22 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/kalendaryo/models/KalAuth.java
> +        this.clientToken = clientToken;
we dont need the clienToken here

2018-01-12 11:36 UTC, barbarasimandi submitted a review, later dismissed

2018-01-12 15:15 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/kalendaryo/LoginActivity.java
> +        kalPref.putString("clienttoken", clientToken);
@dzlica we can have a `setClientToken(String)` method as well in `KalPref`

2018-01-12 15:15 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/kalendaryo/models/KalPref.java
> +        this.putString(kalAuth.getEmail(), value);
@dzlica call addAccount here

2018-01-12 15:15 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/kalendaryo/models/KalPref.java
> +    }
@dzlica have a setClientToken here

2018-01-12 16:03 UTC, closed without merging