Opal 157 removable accounts
green-fox-academy/huli-kalendaryo-android pull request #60
Opened 2018-05-21 16:46 UTC by norvarju

2018-05-22 07:59 UTC, arnikaeva requested changes
Nice work :) only some refactoring needed

2018-05-22 07:59 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/adapter/AccountAdapter.java
> +                alert.setPositiveButton("YES", new DialogInterface.OnClickListener() {
Use 'Yes'

2018-05-22 07:59 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/adapter/AccountAdapter.java
> +                alert.setNegativeButton("NO", new DialogInterface.OnClickListener() {
Use 'No' or 'Cancel'

2018-05-22 07:59 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/ChooseAccountActivity.java
> +    public void getAuthResponse(String clientToken) {
rename AuthResponse

2018-05-22 07:59 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/fragments/AccountsFragment.java
> +        getAuthResponse(kalpref.clientToken());
getAuthResponse() logic is added here and in `ChooseAccountActivity.java` too
maybe could refactor and move the logic into a service?

2018-05-22 07:59 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/ChooseAccountActivity.java
> +
do not leave empty failure blocks, print out the error messages

2018-05-28 08:51 UTC, pataricza1987 submitted a review, later dismissed

2018-05-29 07:41 UTC, arnikaeva approved these changes

2018-05-29 11:53 UTC, pataricza1987 approved these changes

2018-05-29 12:09 UTC, bekobarna approved these changes

2018-05-29 12:10 UTC, merged