OPAL-185 Loading spinner
green-fox-academy/huli-kalendaryo-android pull request #61
Opened 2018-05-22 11:00 UTC by bzita

2018-05-22 14:13 UTC, bekobarna requested changes

2018-05-22 14:13 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/ChooseAccountActivity.java
> -
was this necessary? this way we cannot go back to choosing calendars, if we missed one, because it goes back to the MainActivity

2018-05-22 14:13 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/SelectCalendarActivity.java
> +
onBackPressed again, this way we cannot go back and change the name, if we want to

2018-05-23 11:17 UTC, bekobarna approved these changes

2018-05-24 10:28 UTC, arnikaeva approved these changes
good job :)

2018-05-24 10:58 UTC, merged