Opal 104 backend is able to refresh access tokens
green-fox-academy/huli-kalendaryo-android pull request #65
Opened 2018-05-30 14:55 UTC by sznemeth3

2018-05-31 12:09 UTC, bekobarna submitted a review, later dismissed

2018-05-31 15:38 UTC, arnikaeva requested changes
Nice work, there are some thing that we should discuss however.

2018-05-31 15:38 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/SelectCalendarActivity.java
> +            CURRENT_ATTEMPT = FIRST_ATTEMPT;
the value of `CURRENT_ATTEMPT` won't be valid,
let's say you have 3 accounts and want to query their calendars
1. For the 1st account, you set `CURRENT_ATTEMPT` to be `1`
2. You send a request to Google to get the calendars  -> this is an async request, you won't wait for the result just register the behavior that should happen onResponse or onFailure case
3. Program execution goes back to get the next account
4. You send a request to get the calendars for the 2nd account
...etc

You can't be sure that the response will arrive before you set the `CURRENT_ATTEMPT` to 1 again.

2018-05-31 15:38 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/SelectCalendarActivity.java
> +    public void requestAccessTokenRefresh (GoogleAuth googleAuth) {
refresh token mechanism should be general and not tied to the `requestCalendar` feature
you should move it to an other class and it should not invoke a specific method (in this example `requestCalendars(googleAuth);`

2018-05-31 15:38 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/models/KalPref.java
> +        removeAccount(googleAuth.getEmail());
why is this needed to remove and then add the same mail?

2018-05-31 15:38 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/models/KalPref.java
> +    public void editAuth(GoogleAuth googleAuth) {
almost the same as putAuth method, we should talk about this

2018-06-05 09:20 UTC, arnikaeva requested changes

2018-06-05 09:20 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/SelectCalendarActivity.java
> +                    requestCalendars(account, FINAL_ATTEMPT);
should be `attempt++; requestCalendars(account, attempt);`, so if we change the FINAL_ATTEMPT to be greater than 2 it will still work as expected

2018-06-05 15:52 UTC, bekobarna approved these changes

2018-06-06 13:07 UTC, arnikaeva approved these changes

2018-06-06 14:50 UTC, merged