feat(OPAL-228-Account-and-calendar-should-be-selected):first account …
green-fox-academy/huli-kalendaryo-android pull request #66
Opened 2018-05-31 13:00 UTC by Isshae

…selected by default

2018-05-31 14:47 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/SelectCalendarActivity.java
> +                            Toast.LENGTH_SHORT).show();;
you can use Toast.LENGTH_LONG, so the user can read it properly

2018-05-31 14:47 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/adapter/AccountAdapter.java
> +
why the empty lines were added?

2018-05-31 15:43 UTC, arnikaeva requested changes
Nice work, just minor refactoring needed, let's discuss it :)

2018-05-31 15:43 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/services/AccountService.java
> +                    kalendar.setOutputGoogleAuthId(googleAuths.get(0).getEmail());
should refactor this, discuss it

2018-06-01 08:31 UTC, bekobarna approved these changes

2018-06-05 09:20 UTC, arnikaeva approved these changes

2018-06-05 09:23 UTC, merged