Opal 146 sharing options can be specified in android client
green-fox-academy/huli-kalendaryo-android pull request #67
Opened 2018-06-03 17:26 UTC by sznemeth3

2018-06-04 06:32 UTC, arnikaeva requested changes
Styleguide related fixes :)

2018-06-04 06:32 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/adapter/SharingOptionsAdapter.java
> +            String[] items = new String[]{"Default visibility", "Public", "Private"};
use enum

2018-06-04 06:32 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/adapter/SharingOptionsAdapter.java
> +    Kalendar kalMerged;
naming

2018-06-04 06:32 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/SharingOptionsActivity.java
> +                adapter.removeInputCalendarIds();
why are we removing this?

2018-06-04 06:32 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/SharingOptionsActivity.java
> +        RecyclerView recKal = findViewById(R.id.sharing_options_list);
naming

2018-06-04 06:32 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/SharingOptionsActivity.java
> +        Kalendar kalMerged = (Kalendar) getIntent().getSerializableExtra("list");
naming for `kalMerged` and for `list`

2018-06-04 06:32 UTC, arnikaeva commented on app/src/main/res/layout/activity_select_calendar.xml
> +        android:id="@+id/gotosharingoptions"
for resource naming, check:
https://github.com/umesh0492/android-guidelines/blob/master/project_and_code_guidelines.md
**2.3.2 Resources naming**

2018-06-05 07:50 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/SelectCalendarActivity.java
> +        recyclerView = findViewById(R.id.listView);
why are we calling it a recyclerview and than call it a listview in the xml?

2018-06-05 07:50 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/SharingOptionsActivity.java
> +                new DividerItemDecoration(recyclerView.getContext(),
indentation

2018-06-05 07:50 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/adapter/GoogleCalendarAdapter.java
> +        void removeCalendar(GoogleCalendar calderTitle);
caldertitle?

2018-06-05 07:50 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/adapter/SharingOptionsAdapter.java
> +}
put an empty line at the end

2018-06-05 09:17 UTC, arnikaeva requested changes
Minor comments

2018-06-05 09:17 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/adapter/SharingOptionsAdapter.java
> +    public enum VisibilityOptions{
do not use plural for enum names, `VisibilityOption` is fine

2018-06-05 09:17 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/models/GoogleCalendar.java
> +    String sharingOptions;
type for sharingOption should be VisibilityOption enum, so it cannot take other value

2018-06-05 10:09 UTC, bekobarna submitted a review, later dismissed

2018-06-05 10:26 UTC, arnikaeva requested changes

2018-06-05 10:26 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/adapter/SharingOptionsAdapter.java
> +        calendar.setSharingOption(VisibilityOption.valueOf("DEFAULT"));
I think you can access it like VisibilityOption.DEFAULT

2018-06-05 10:26 UTC, arnikaeva commented on app/src/main/java/com/greenfox/kalendaryo/adapter/SharingOptionsAdapter.java
> +    public enum VisibilityOption{
move it to its own file (VisibilityOption.java)

2018-06-05 11:17 UTC, bekobarna approved these changes

2018-06-05 12:42 UTC, arnikaeva approved these changes

2018-06-05 12:43 UTC, merged