Opal 136 preview for merged kalendar
green-fox-academy/huli-kalendaryo-android pull request #75
Opened 2018-06-14 10:58 UTC by norvarju

The preview displays every calendar event of the user with random colors in a swipable format. The preview activity gets displayed with 5 seconds delay due to the data retrieval from google API. When submiting preview the app navigates back to kalendar fragment with 500 milisecond delay because the backend API gets called on button click, and with no delay the newly merged calendar does not get displayed on the kalendar fragment.

2018-06-14 11:27 UTC, bekobarna requested changes

2018-06-14 11:27 UTC, bekobarna commented on app/src/main/AndroidManifest.xml
> +        <!-- <activity android:name=".StaticWeekViewActivity" /> -->
we dont need this line

2018-06-14 11:27 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/BaseActicity.java
> +package com.greenfox.kalendaryo;
BaseActicity??

2018-06-14 11:27 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/LoginActivity.java
> +            //Toast.makeText(this, "Saved!", Toast.LENGTH_LONG).show();
why is it commented out?

2018-06-14 11:27 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/LoginActivity.java
> +        //Toast.makeText(this, "Sorry, you can't add the account you are already logged into!", Toast.LENGTH_LONG).show();
same here

2018-06-14 11:27 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/StaticWeekViewActivity.java
>          event.setColor(getResources().getColor(R.color.event_color_01));
we can remove the whole Activity if we dont use it

2018-06-14 11:27 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/fragments/KalendarFragment.java
> +
why the empty line?

2018-06-14 11:27 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/http/RetrofitClient.java
> +    static String BASE_URL_BACKEND = "http://kalendaryobackenddev-env.um8evv5pid.eu-west-3.elasticbeanstalk.com/";
use the default BuildConfig.LOCAL_IP_ADDRESS, not the deployed version

2018-06-14 11:27 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/services/WeekViewService.java
> +package com.greenfox.kalendaryo.services;
why the empty file?

2018-06-18 08:17 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/ChooseAccountActivity.java
> +        Bundle bundle2 = new Bundle();
maybe rename from bundle2 to something better

2018-06-18 08:17 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/WeekViewActivity.java
> +    private GoogleApi googleApi;
we can use Dagger to have GoogleApi and BackendApi in this activity

2018-06-18 08:17 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/WeekViewActivity.java
> +        sendToBackend.setOnClickListener(new View.OnClickListener() {
replace this onClickListener with lambda, just like in other acitivities

2018-06-18 08:17 UTC, bekobarna commented on app/src/main/java/com/greenfox/kalendaryo/services/EventService.java
> +    private GoogleApi googleApi;
use Dagger to inject GoogleApi

2018-06-19 11:21 UTC, pataricza1987 submitted a review, later dismissed

2018-06-20 11:39 UTC, bekobarna approved these changes

2018-06-20 11:43 UTC, pataricza1987 approved these changes

2018-06-20 11:44 UTC, merged